### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by Gonzih**
Hi there,

Since this repo mentions running pluto in docker here is Dockerfile I use to work with Pluto.

Hope this is helpful!

### CODE REVIEW

**Comment by pankgeorg** [comment]
Hi @Gonzih !! This is amazing, do I understand correctly that this works based on a gpu-friendly image?

If so - can you rename it to `Dockerfile-cudagpu`, and add some README or an example Pluto Notebook where you parallelize something interesting?!

Thank you!! 💫💫

**Comment by Gonzih** [comment]
@pankgeorg done, i think this is much better looking README, I moved everything cuda related to a separate folder just to keep it cleaner.

Cheers!

**Comment by pankgeorg** [comment]
That's great @Gonzih ! I'm merging this - I'll also create packages in ghcr.io soon - can I ping you if I need help then? :)

**Comment by Gonzih** [comment]
Any time my friend! Don't hesitate to ask for help :)

**Pull request merged**
